version: '3.8'

services:
  db:
    image: mongo
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  amw:
    build:
      context: .
      target: development
    env_file: [ .env.dev ]
    ports:
      - 8080:8080
    volumes:
      - .:/src
      - /src/node_modules/
      - /src/dist/
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URI: "mongodb://root:password@db:27017/amw?authSource=admin"

  mongoclient:
    image: mongoclient/mongoclient
    ports:
      - 5151:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      MONGO_URL: "mongodb://root:password@db:27017/mongoclient?authSource=admin"
      MONGOCLIENT_DEFAULT_CONNECTION_URL: "mongodb://root:password@db:27017/amw?authSource=admin"
