version: '3.6'

services:
  db:
    image: mongo
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  amw:
    build: .
    env_file: [.env.dev]
    command: ["/bin/sh", "-c", "npm run start:docker"]
    ports:
      - 8080:8080
      - 5858:5858
    volumes:
      - .:/src
      - /src/node_modules/
    depends_on: 
      db:
        condition: service_healthy
    environment:
      DATABASE_URI: "mongodb://root:password@db:27017/todo?authSource=admin"