version: '3.8'

services:
  db:
    image: mongo:6
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  amw:
    build: ./
    env_file: [ .env.dev ]
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URI: "mongodb://root:password@db:27017/amw?authSource=admin"
